name: ci

on:
  push:
    branches:
      - "main"
  
  pull_request:
    branches:
      - "*"  
    tags:
      - "*"

jobs:
  test:
    defaults:
      run:
        working-directory: go/src/github.com/sock-shop-demo/catalogue-microservice
    runs-on: ubuntu-latest
    env:
      GROUP: weaveworksdemos
      COMMIT: ${{ github.sha }}
      REPO: catalogue
      GO_VERSION: 1.7.5
      GOPATH: /home/runner/work/catalogue/catalogue/go

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: go/src/github.com/sock-shop-demo/catalogue-microservice

      - uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup PATH
        run: echo "::add-path::${GOPATH}/bin"

      - name: Install dependencies
        run: go get -u github.com/FiloSottile/gvt && gvt restore && go get -v github.com/mattn/goveralls

      - name: Build
        run: ./scripts/build.sh

      - name: Unit Test
        run: ./test/test.sh unit.py

      - name: Test Docker Image
        run: ./test/test.sh container.py

      # Push to dockerhub
      - name: Push catalogue to Docker Hub
        uses: docker/build-push-action@v1
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          dockerfile: go/src/github.com/sock-shop-demo/catalogue-microservice/docker/catalogue/Dockerfile
          path: go/src/github.com/sock-shop-demo/catalogue-microservice
          repository: lautibringas/catalogue
          tag_with_ref: true
          tag_with_sha: true