name: ci

on:
  push:
    branches:
      - "main"
  
  pull_request:
    branches:
      - "*"  
    tags:
      - "*"

jobs:
  test_build:
    defaults:
      run:
        working-directory: go/src/github.com/sock-shop-demo/catalogue-microservice
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}
      STAGING_KUBERNETES_KUBECONFIG: ${{ secrets.STAGING_KUBERNETES_KUBECONFIG }}
      PRODU_KUBERNETES_KUBECONFIG: ${{ secrets.PRODU_KUBERNETES_KUBECONFIG }}
      REPO: catalogue
      GO_VERSION: 1.7.5
      GOPATH: /home/runner/work/catalogue/catalogue/go

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: go/src/github.com/sock-shop-demo/catalogue-microservice

      - uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup PATH
        run: echo "::add-path::${GOPATH}/bin"

      - name: Install dependencies
        run: go get -u github.com/FiloSottile/gvt && gvt restore && go get -v github.com/mattn/goveralls

      - name: Unit Test
        run: ./test/test.sh
      
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: coverage.out

      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true

      - name: Build
        run: ./scripts/build.sh

      - name: Push catalogue to Docker Hub
        run: | 
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
          docker push lautibringas/catalogue

  sonarCloud:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}
      STAGING_KUBERNETES_KUBECONFIG: ${{ secrets.STAGING_KUBERNETES_KUBECONFIG }}
      PRODU_KUBERNETES_KUBECONFIG: ${{ secrets.PRODU_KUBERNETES_KUBECONFIG }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
    
      - name: Get kubectl
        uses: azure/setup-kubectl@v1
    
      - name: Deploy to staging
        run: ./deploy/deploy_staging.sh